name: Deploy to Vercel

on:
  push:
    branches: [ dev ]  # Change to your main branch name if different
  workflow_dispatch:    # Allows manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Vercel Deployment
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }})
          if [ $response -eq 200 ] || [ $response -eq 201 ]; then
            echo "✅ Deployment triggered successfully"
          else
            echo "❌ Deployment failed with status code: $response"
            exit 1
          fi
